# Use the official Python image
FROM python:3.10

# Set environment variables to prevent Python from writing .pyc files
# and to buffer stdout and stderr (useful for logging)
ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

# Set the working directory in the container
WORKDIR /codingchallenge

# Install dependencies
COPY requirements.txt /codingchallenge/
RUN pip install --upgrade pip && pip install -r requirements.txt

# Copy the rest of the application code
COPY . /codingchallenge/

# Expose the port the app runs on
EXPOSE 8000

# Run the main.py script
CMD ["python", "app.py"]
